### ISSUE TITLE
exported var Log should have its own declaration

### ISSUE THREAD

**Issue by JeremyRand** [hlandau/xlog#6]
It appears that xlog's recommended syntax (`var log, Log = xlog.NewQuiet("my.logger.name")`) isn't consistent with standard Go style guidelines.  As a result, `golint` outputs the following warning:

~~~
exported var Log should have its own declaration
~~~

The relevant part of `golint`'s source code is at https://github.com/golang/lint/blob/db11711f6af331c079dd1a0fec19fdad6c86a18f/lint.go#L870 .

**Comment by hlandau** [comment]
Unfixable.
